version: '3'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - /tmp/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  cassandra-001:
    image: cassandra:3.11
    container_name: cassandra-001
    ports:
      - 9042:9042
    volumes:
        - /tmp/cassandra:/var/lib/cassandra
